version: '3.0'
services:
  postgres:
    image: postgres:11.4
    container_name: codefy_postgres_service
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - codefy-network
    restart: unless-stopped

volumes:
  postgres:

networks:
  codefy-network:
    driver: bridge
