version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wp_bten"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
volumes:
  mysql:
